---
#ADM_POC: "Local Admin, admin@admin.com"

# VERSIONS - NAMES
GUAC_VER: "1.2.0" # Latest stable version of Guac from https://guacamole.apache.org/releases/
GUAC_SERVER: "guacamole-server-{{ GUAC_VER }}"
GUAC_CLIENT: "guacamole-{{ GUAC_VER }}"
GUAC_JDBC: "guacamole-auth-jdbc-{{ GUAC_VER }}"
GUAC_TOTP: "guacamole-auth-totp-{{ GUAC_VER }}"
MYSQL_CON_VER: "8.0.20"
MYSQL_CON: "mysql-connector-java-{{ MYSQL_CON_VER }}"

# PORTS
#GUAC_PORT: "4822"
#MYSQL_PORT: "3306"

# KEY SIZES
#JKSTORE_KEY_SIZE_DEF: "4096" # Default Java Keystore key-size
#LE_KEY_SIZE_DEF: "4096" # Default Let's Encrypt key-size
#SSL_KEY_SIZE_DEF: "4096" # Default Self-signed SSL key-size

# DEFAULT CREDENTIALS
#MYSQL_PASSWD_DEF: "guacamole" # Default MySQL/MariaDB root password
#DB_NAME_DEF: "guac_db" # Default database name
#DB_USER_DEF: "guac_adm" # Default database user name
#DB_PASSWD_DEF: "guacamole" # Default database password
#JKS_GUAC_PASSWD_DEF: "guacamole" # Default Java Keystore password
#JKS_CACERT_PASSWD_DEF: "guacamole" # Default CACert Java Keystore password, used with LDAPS

# URLS
GUAC_URL: "https://apache.org/dyn/closer.cgi?action=download&filename=guacamole/{{ GUAC_VER }}/"
MYSQL_CON_URL: "https://dev.mysql.com/get/Downloads/Connector-J/"

# DIR & FILE NAMES
#GUAC_CONF: "guacamole.properties" # Guacamole configuration/properties file
#MYSQL_CON: "mysql-connector-java-${MYSQL_CON_VER}"


## YUM REPOS - PACKAGES
FUSION_REPOS:
  - https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm
  - https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm
REQUIRED_DEPENDENCIES:
  - cairo-devel
  - ffmpeg-devel
  - freerdp-devel
  - freerdp-plugins
  - gcc
  - gnu-free-mono-fonts
  - libjpeg-turbo-devel
  - libjpeg-turbo-official
  - libpng-devel
  - libssh2-devel
  - libtelnet-devel
  - libvncserver-devel
  - libvorbis-devel
  - libwebp-devel
  - libwebsockets-devel
  - mariadb
  - mariadb-server
  - nginx
  - openssl-devel
  - pango-devel
  - policycoreutils-python
  - pulseaudio-libs-devel
  - setroubleshoot
  - tomcat
  - uuid-devel

## DIRECTORIES
LIB_DIR: "/var/lib/guacamole/"
INSTALL_DIR:  "/usr/local/src/guacamole/{{ GUAC_VER }}/"
NEW_DIRS:
  - "/etc/guacamole"
  - "/var/lib/guacamole/lib"
  - "/var/lib/guacamole/extensions"
  - "{{ INSTALL_DIR }}client"
  - "{{ INSTALL_DIR }}selinux"
  - "/usr/share/tomcat/.guacamole"
